baseURL = "http://example.com/"
languageCode = "en-us"
title = "Gianluca Della Vedova"
theme = "minimal"
disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = ""

[params]
    author = "Gianluca Della Vedova"
    description = "Personal blog theme powered by Hugo"
    githubUsername = "gdv"
    accent = "darkcyan"
    showBorder = true
    backgroundColor = "white"
    font = "Fira Sans"
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["SQL", "YAML", "Rust", "Python", "Makefile", "Markdown"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 3

[[menu.main]]
    url = "/project/"
    name = "Projects"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.


[[menu.icon]]
url = "mailto:gianluca@dellavedova.org"
name = "fas fa-envelope"
weight = 1

[[menu.icon]]
url = "https://github.com/gdv/"
name = "fab fa-github"
weight = 2

[[menu.icon]]
url = "https://orcid.org/0000-0001-5584-3089"
name = "fab fa-orcid"
weight = 4

[[menu.icon]]
url = "https://scholar.social/@dellavg"
name = "fab fa-mastodon"
weight = 4

[[menu.icon]]
url = "https://stackoverflow.com/users/34613/gianluca-della-vedova"
name = "fab fa-stack-overflow"
weight = 5
